### ISSUE TITLE
The Docker host machine only requires Nvidia Drivers

### ISSUE THREAD

**Issue by KinmanLam** [tensorflow/community#1]
Currently, the Docker install GPU support instructions here:
https://www.tensorflow.org/install/install_linux#gpu_support 

Indicates it requires the full CUDA toolkit, cuDNN, and Nvidia drivers as outlined in:
https://www.tensorflow.org/install/install_linux#NVIDIARequirements

The document should be changed to indicate the host machine (running the container) requires only Nvidia drivers. See:
https://github.com/nvidia/nvidia-docker/wiki/CUDA#requirements

The container itself requires only the CUDA toolkit, cuDNN and Docker file can be found here:
https://hub.docker.com/r/nvidia/cuda/

**Comment by ewilderj** [comment]
Please re-file this issue on tesnorflow/tensorflow. The community repo is for managing contributor processes.
