### ISSUE TITLE
Will tensorflow 2.0 directly support sequence-to-sequence RNN models?

### ISSUE THREAD

**Issue by npuichigo** [tensorflow/community#106]
I saw that tf.contrib.seq2seq has been moved to tensorflow addons, so is that the recommended way to use seq2seq rnn models? Or maybe tensorflow 2.0 will directly support it?

**Comment by seanpmorgan** [comment]
Yes installing tf-addons will be the recommended way to use seq2seq models in TF2:
https://github.com/tensorflow/addons/tree/master/tensorflow_addons/seq2seq

This is part of the effort  to make TF more modular and have better maintenance of community code (i.e. tf.contrib)

**Comment by npuichigo** [comment]
Thanks!
