### ISSUE TITLE
ImportError: cannot import name 'check_scalar'

### ISSUE THREAD

**Issue by KseniaErshova** [tensorflow/community#108]
ImportError                               Traceback (most recent call last)
<ipython-input-11-9b6ccb88fd0a> in <module>()

----> 3 import sklearn
      4 from sklearn.cluster import KMeans as km
      5 from sklearn.preprocessing import StandardScaler

./anaconda3/envs/py35/lib/python3.5/site-packages/sklearn/__init__.py in <module>()
     74 else:
     75     from . import __check_build
---> 76     from .base import clone
     77     from .utils._show_versions import show_versions
     78 

./anaconda3/envs/py35/lib/python3.5/site-packages/sklearn/base.py in <module>()
     14 
     15 from . import __version__
---> 16 from .utils import _IS_32BIT
     17 
     18 _DEFAULT_TAGS = {

./anaconda3/envs/py35/lib/python3.5/site-packages/sklearn/utils/__init__.py in <module>()
     18 from ..exceptions import DataConversionWarning
     19 from .deprecation import deprecated
---> 20 from .validation import (as_float_array,
     21                          assert_all_finite,
     22                          check_random_state, column_or_1d, check_array,

ImportError: cannot import name 'check_scalar'

**Comment by mayou36** [comment]
Hi Ksenia, it seems that this is about scikit learn and neither about TensorFlow nor about community proposals for TensorFlow. Please post an issue at the right place.

**Comment by ewilderj** [comment]
Apologies, but this issue tracker is for TF Community governance. I encourage you to address questions to the tensorflow/tensorflow issue tracker, discuss@tensorflow.org or StackOverflow.
