### ISSUE TITLE
TensorFlow C API tutorial

### ISSUE THREAD

**Issue by alejandro-colomar** [tensorflow/community#118]
There is a tutorial for TF in python, a smaller guide for the C++ API, but there is absolutely nothing for the C API.

Is there any help for starting to use TF in C?

**Comment by vinodgro** [comment]
+1 for a tutorial on TF in C.

Where can I find the guide on TF C++ API?

**Comment by alejandro-colomar** [comment]
TF C++ guide:
https://www.tensorflow.org/guide/extend/cc

**Comment by singh728om** [comment]
https://www.tensorflow.org/install/lang_c
Here is C API tutorials you can ....see

**Comment by alejandro-colomar** [comment]
That's not a tutorial about the C API.  That only tells me how to install the C API, but absolutely nothing about the API itself.  It doesn't tell me which functions I do have available and what they do.

**Comment by bhack** [comment]
@alejandro-colomar Check [this thread](https://groups.google.com/a/tensorflow.org/forum/m/#!topic/developers/3X6GrdTpxWo).
Seems that generally c/c++ it Is not so much user oriented or at last having "user care"

**Comment by ewilderj** [comment]
Apologies, but this issue tracker is for TF Community governance. I encourage you to address questions to the tensorflow/docs issue tracker, or docs@tensorflow.org
