### ISSUE TITLE
Broken link in Tensorflow 2.0 overview

### ISSUE THREAD

**Issue by gerritholl** [tensorflow/community#120]
The [Tensorflow 2.0 overview](https://github.com/tensorflow/community/blob/master/sigs/testing/faq.md) in the section "General", subsection "Should I start learning TensorFlow 1.x or TF 2.0?", links to https://www.deeplearning.ai/tensorflow-from-basics-to-mastery/ under the anchor "DeepLearning.ai Course".  However, this link results in Error 404 "No Results Found".  Is it the same as [this course on coursera](https://www.coursera.org/learn/introduction-tensorflow)?

**Comment by ewilderj** [comment]
Apologies, but this issue tracker is for TF Community governance. I encourage you to address questions to the tensorflow/docs issue tracker, discuss@tensorflow.org or StackOverflow.
