### ISSUE TITLE
Add a custom Op

### ISSUE THREAD

**Issue by huang229** [tensorflow/community#121]
How to add a custom op in Windows system?thank you!!!

**Comment by seanpmorgan** [comment]
This is not really the right place for this question (try tensorflow/custom-op or stackoverflow), but anyways...

If you build tensorflow from source and compile the op during build it's possible to do at the moment. A more modular way would be to link to a pre-compiled libtensorflow. See this issue:
https://github.com/tensorflow/custom-op/issues/24
