### ISSUE TITLE
Invalid Email for Project Steward

### ISSUE THREAD

**Issue by Yomdroid** [tensorflow/community#132]
I tried sending an email to project steward Sarah Novotny, please can the email be reviewed?

<img width="1118" alt="Screenshot 2019-08-09 at 2 24 41 PM" src="https://user-images.githubusercontent.com/32799642/62782152-8aabbf80-bab1-11e9-8256-0606315a778f.png">

**Comment by ewilderj** [comment]
We did update this. Please reach out to me ewj@google.com if you have Code of Conduct issues.
