### ISSUE TITLE
Building Tensorflow API in ./configure.py comma-separated list does not work correctly

### ISSUE THREAD

**Issue by dmitryponv** [tensorflow/community#134]
The comma-separated lsit does not function correctly, 
If I input the library folder first, it finds it but complains about the include folder, 
If I inptu the include folder first, it complains about the library folder 

> Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:
> 
> 
> Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:
> 
> 
> Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: **C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include, C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64**
> 
> 
> **Could not find any cudart.lib in any subdirectory:**
>         ''
>         'lib64'
>         'lib'
>         'lib/*-linux-gnu'
>         'lib/x64'
>         'extras/CUPTI/*'
> of:
>         'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include'
> Asking for detailed CUDA configuration...
> 
> Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]:
> 
> 
> Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]:
> 
> 
> Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: **C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\lib\x64 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\include**
> 
> 
> **Could not find any cuda.h matching version '10' in any subdirectory:**
>         ''
>         'include'
>         'include/cuda'
>         'include/*-linux-gnu'
>         'extras/CUPTI/include'
>         'include/cuda/CUPTI'
> of:
> Asking for detailed CUDA configuration...
>

**Comment by MachineJeff** [comment]
Hi, I have solved it in Linux but not Windows.
use `find -name cudart.lib` to find the lost file.
paste the path on `Please specify the comma-separated list of base paths to look for CUDA libraries and headers.`
do not forget use comma-separated. Good lock

**Comment by ewilderj** [comment]
Apologies, but this issue tracker is for TF Community governance. I encourage you to address questions to the tensorflow/tensorflow issue tracker, discuss@tensorflow.org or StackOverflow.
