### ISSUE TITLE
KeyError while loading image data.

### ISSUE THREAD

**Issue by DKWIPL** [tensorflow/community#137]
**Error:**
File "DataCollection.py", line 38, in caption_image
    return "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])
KeyError: 'sunflowers\\6166888942_7058198713_m.jpg'

**Function:**
def caption_image(image_path):
    image_rel = pathlib.Path(image_path).relative_to(data_root)
    return "Image (CC BY 2.0) " + ' - '.join(attributions[str(image_rel)].split(' - ')[:-1])

It gives a KeyError while returning the parameter.
And every time it gives a KeyError with different image name and path. 

Any idea on this?

**Comment by ewilderj** [comment]
Apologies, but this issue tracker is for TF Community governance. I encourage you to address questions to discuss@tensorflow.org or StackOverflow.
