### ISSUE TITLE
Tensorflow js with Node js?

### ISSUE THREAD

**Issue by jt4000** [tensorflow/community#157]
Hello,

Do you also need to install nodejs in order to use tensorflow js?

Or is it only enough to use tensorflow js?

Thank you!

**Comment by rish-16** [comment]
Hey there!

TensorFlow.js is built using node.js. You need to have [`node`](https://nodejs.org/en/download/) installed on your system to use TF.js. You can install TensorFlow.js using `npm` or `yarn` in your command prompt like so:

```bash
npm install @tensorflow/tfjs
```

```bash
yarn add @tensorflow/tfjs
```

Do ensure you are in your project directory.

Hope this helps!

PS. if you have any other questions, do drop them down below!

**Comment by ewilderj** [comment]
Please use the tfjs@tensorflow.org group for these questions, this repo is rarely monitored.
