### ISSUE TITLE
Scope of MLIR

### ISSUE THREAD

**Issue by adityaatluri** [tensorflow/community#158]
Hi,
Is MLIR going to be focusing on just Tensorflow or open to enabling projects like for example, Halide or tensor-contractions or graphics (DX12 shaders) etc

@tatianashp

**Comment by tatianashp** [comment]
MLIR applications are not restricted to TensorFlow. We are open to any use
that benefits the community. One current notable example of non-TensorFlow
application is Flang
<http://llvm.org/devmtg/2019-10/talk-abstracts.html#tech19>. I am looking
forward to seeing other interesting use cases.

Thanks,
Tatiana
