### ISSUE TITLE
TypeError: The added layer must be an instance of class Layer. Found: <keras.layers.core.Dropout object

### ISSUE THREAD

**Issue by Neel-Gupta** [tensorflow/community#159]
Getting error in Tensor Flow while running it in Google colab. I am getting this: ====>

> _TypeError: The added layer must be an instance of class Layer. Found: <keras.layers.core.Dropout object_

THE Code is :============>
`
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers.core import Dense, Dropout
from tensorflow.keras.layers.recurrent import LSTM

mnist = tf.keras.datasets.mnist
(x_train ,y_train),(x_test,y_test) = mnist.load_data()

model = tf.keras.Sequential();
model.add(Dropout(0.2))

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(10, activation='softmax'))`

MY versions are :--------
**TensorFLow  ~~  1.14
Keras ~~ 2.24**

Since the code which I am using is quite correct(I think) the problem must be with TensorFlow or Keras....

**Comment by Neel-Gupta** [comment]
The problem has been solved by me. The correct code is :======>
`
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.layers import LSTM


mnist = tf.keras.datasets.mnist
(x_train ,y_train),(x_test,y_test) = mnist.load_data()
print ("The shape of of x_train: ", x_train.shape)
print (x_train[0].shape)

model = Sequential()

model.add(Dropout(0.2))

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.1))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(10, activation='softmax'))
`

**Comment by zulfiqarAlibalti** [comment]
thanku

**Comment by zulfiqarAlibalti** [comment]
thanku soo  much sir

**Comment by keithmartinkinyua** [comment]
i really cant see the difference between the two pieces of code

**Comment by BIGINCHI** [comment]
> i really cant see the difference between the two pieces of code

tf.keras.Sequential
