### ISSUE TITLE
Using four spaces for indentation in the Python docs? As a sign of good will towards the open source community. 

### ISSUE THREAD

**Issue by gabrieldemarmiesse** [tensorflow/community#160]
This issue is absolutely not a debate about if four spaces is better than two spaces for indentation in python. Please avoid comments mentioning that. 

This is more about the image that the tensorflow project gives to contributors and the open source community in general. 

Currently this image is more "We are making this cool tool at Google, you can use it for free, and help us make it better".

We should try to move towards "Tensorflow is community driven, it's open source first. Google is heavily involved in it, so it's expected that the dev workflows of Googlers goes first. "

I understand that moving to four spaces per indentation for Python in the codebase is hard because of the git blame being overwritten and maybe other tools at Google. Also huge git conflicts in perspective. 

But for the documentation it's different. First it's seen by a lot more people, so the impact is much much bigger for the image of TF. Some beginners start Python by learning Tensorflow. Let's give them Python practices recommended by pep8, the open source standard, not Google. There is less activity per line of code, so less chances of conflicts. And the git blame is not critical in the documentation. 
I believe that changing the indentation in the docs would not be that hard technically speaking. Maybe time consuming at worst. 

Let's make Tensorflow feel open-source first!

@dynamicwebpaige do you think I should do a pull request with a RFC? If so, would you endorse it?

**Comment by ewilderj** [comment]
Please could you transfer this conversation to docs@tensorflow.org or developers@tensorflow.org -- this repo is not monitored for this purpose.

**Comment by gabrieldemarmiesse** [comment]
Thanks @ewilderj !
