### ISSUE TITLE
Application to become a Google Code-In 2019 mentor for TensorFlow

### ISSUE THREAD

**Issue by arghyadeep99** [tensorflow/community#174]
I wish to apply for becoming a mentor for Google Code-In 2019. I have done several projects in Deep Learning. I feel it will be an amazing opportunity for me to become a part of the Google Code-In event as mentor on behalf of TensorFlow, the framework that has helped me build some cool projects. I am providing links to my LinkedIn and GitHub profile: 

[LinkedIn](https://www.linkedin.com/in/arghyadeep-das-05425a14a/)
[GitHub](http://github.com/arghyadeep99)

P.S.: Since I am not sure about how to approach TensorFlow on becoming a mentor for Google Code-In, I am creating an issue for it. Kindly let me know if there is some other way that I should follow for becoming a mentor.

**Comment by sgpritam** [comment]
Thanks for the application for being a mentor in Google Code In program. We are excited to review them and welcome you to the Tensorflow community. There are new guidelines from google to select mentors based on the contribution and the trust. We can't select the mentors based on the submitted form alone. We are also reviewing the list of mentors who are already got selected.
We want to ensure that mentors
Are familiar with the codebase, did some contributions (pull requests, design documents, issue triaging etc) and the activity in the community

**Comment by sgpritam** [comment]
#173 Thanks for the application for being a mentor in Google Code In program. We are excited to review them and welcome you to the Circuitverse community. There are new guidelines from google to select mentors based on the contribution and the trust. We can't select the mentors based on the submitted form alone. We are also reviewing the list of mentors who are already got selected.
We want to ensure that mentors
Are familiar with the codebase, did some contributions (pull requests, design documents, issue triaging etc) and the activity in the community(including this slack group)

**Comment by sakshivij** [comment]
@sgpritam How can anyone get connected via slack ? I couldn't find anything related to slack channel. I would like to be part of the channel and contribute as a beginner.

**Comment by sgpritam** [comment]
@sakshivij please check again and edit your comment

**Comment by sgpritam** [comment]
#173 Thanks for the application for being a mentor in Google Code In program. We are excited to review them and welcome you to the Tensorflow community. There are new guidelines from google to select mentors based on the contribution and the trust. We can't select the mentors based on the submitted form alone. We are also reviewing the list of mentors who are already got selected.
We want to ensure that mentors

**Comment by arghyadeep99** [comment]
So what exactly should we be doing now? @sgpritam

**Comment by sgpritam** [comment]
Contribute and be active regularly, then the organization will select the active member @arghyadeep99

**Comment by bhack** [comment]
@ewilderj Can we close this?
