### ISSUE TITLE
Becoming a mentor for Google Code-In 2019

### ISSUE THREAD

**Issue by raghavpuri** [tensorflow/community#176]
I wish to become a mentor for Google Code-in 2019. I have done a number of ML projects and I've been a Google Code-In Finalist in 2018. My main areas of expertise are Computer Vision. I also do digital design. I'd be happy to send in a resume and more details as well, please let me know if there's an official email or form.

NOTE: As I am not sure how to approach TensorFlow on becoming a mentor for Google Code-in, I am creating an issue for it. Kindly let me know if there is some other way that I should follow for applying.

**Comment by bhack** [comment]
@ewilderj Can we close this?

**Comment by ematejska** [comment]
Closing since this is already over.
