### ISSUE TITLE
Where is staging package in tf2? Originally from tensorflow.contrib.staging import StagingArea

### ISSUE THREAD

**Issue by YunchuZhang** [tensorflow/community#178]
# Community repo

The only issues you should file here concern the community's documentation or processes.

All other bugs should be filed on the appropriate repo, questions directed to the various email groups, or if it's a "how-to" question, StackOverflow.

Hi there,
I just see the list about tf.contrib package, and see that staging is deleted since redundant , i want to ask that which function or package could replace this?

**Comment by Squadrick** [comment]
`tf.data` is now the canonical way of dealing with all "data" including the transfer of tensors from CPU to GPU and vice-versa. I could help you out more if you mention how exactly you were using `tf.StagingArea`.

**Comment by yongtang** [comment]
I could see it is quite closely related to I/O. If there is enough interest we could help having a similar method exposed in [tensorflow/io](https://github.com/tensorflow/io) package .

**Comment by bhack** [comment]
@ematejska Can we close this?

**Comment by ematejska** [comment]
Since the question was answered.  Closing.
