### ISSUE TITLE
Becoming a mentor for Google Code-in'19

### ISSUE THREAD

**Issue by rajatsahay** [tensorflow/community#181]
I wanted to become a mentor for Tensorflow for Google Code-in 2019. However, there seems to be no certain way to approach the organization, hence, why I am creating an issue here. 
I have a great interest in Machine Learning and specialize in Computer Vision. Given the opportunity, I would be more than happy to submit my CV for review. 

If there is a proper path to approaching the organization, kindly inform me and I shall go there.

**Comment by tanmoyio** [comment]
Have you personally DM your email id to Paige Bailey where she announced for mentor's registration in Google Code-in 2019?

If yes, then create a set of initial tasks before deadline, take the survey sent by Paige Bailey. And you are good to go.

If no, don't worry. You can anytime contribute in Tensorflow. This guide might help- https://www.tensorflow.org/community/contribute , there are many ways to contribute. Better start with the easier one then dive deeper.

You don't need to approach to organization directly to be a part of the community or send the CV. This applies for any open source organization. 

Hope it might helped.
And the issue should be closed.
