### ISSUE TITLE
Best way to contact mentors GCI 2019

### ISSUE THREAD

**Issue by neelr** [tensorflow/community#183]
Hi!

Hi! Just asking about GCI and the contacting mentors part, is there any IRC channel or Slack channel that we should join, or should we just ask here (the chat and email list redirect to this repository.

Thanks so much!

**Comment by ayanujju** [comment]
Hey @neelr, you can reach out to mentor for a specific task through the task comment section. We don't have any dedicated group for mentor-mentee discussion this time. Hope this helps. 

All the best for GCI tasks :)

**Comment by bhack** [comment]
Can we close this?
