### ISSUE TITLE
A few links are broken

### ISSUE THREAD

**Issue by alisaaalehi** [tensorflow/community#191]
Links in the following sentences are broken, please consider fixing them:
> Pix2Pix (Example Colab)

> NMT Model (Example Colab)

> Dcgan (Example Colab)

> ... take a look at tf.Module. (Variables, Custom Layers) ...

> ... For further information, see our tutorials here and

> ... and running a saved model in TensorFlow 2.0.

**Comment by LexusH** [comment]
Thank you for the feed back! I'll look into fixing these links immediately!

**Comment by bhack** [comment]
Can we close this?
