### ISSUE TITLE
Discord Discourse

### ISSUE THREAD

**Issue by bhack** [tensorflow/community#204]
For a so large community we have really a very low traffic Dev mailing lists so I suppose something It Is not working in the community comunication infra.

I propose with a rationale quite to [LLVM community](http://lists.llvm.org/pipermail/llvm-dev/2019-November/136880.html) to setup ad adopt an unique Discord and Discourse for Dev and the SIGs.

**Comment by tataudat** [comment]
Second this. Please make it happen.

**Comment by bhack** [comment]
Another alternative for Discord: https://about.riot.im/

**Comment by bhack** [comment]
For MLIR is working quite well: https://llvm.discourse.group/c/llvm-project/mlir/ /cc @ewilderj

**Comment by ewilderj** [comment]
cc / @theadactyl 

@bhack consider the vast footprint on StackOverflow, which is where we intentionally sent a lot of questions from the beginning, so mailing list traffic isn't everything here. There are downsides to having too much traffic impeding developer velocity...

All that said, we definitely recognize this need too and are investigating.

**Comment by bhack** [comment]
@ewilderj By a pure theoretically point of view I could understand what you mean and could be ok to forward stackoverflow "classical" traffic on stackoverflow. 

But I still see too few public discussion about the project and probably all it is very restricted on this `community repository` with issue and RFC PR and these kinds of things cannot be discussed on stackoverflow. Probably could be discusses on dev mailing list but there is just random sparse traffic there.

I suppose that riot(matrix)/discord and discourse could really expand p2p communication in the community.

I don't know if the developer velocity was impacted with [Pytorch discuss](https://discuss.pytorch.org/) or in LLVM. 

I think this always depend on the expanded p2p community self-sustain abilities and the core team effort to share internal as possibile.

**Comment by bhack** [comment]
See also the quite recent switch of Mozilla on Matrix https://matrix.org/blog/2019/12/19/welcoming-mozilla-to-matrix

**Comment by bhack** [comment]
I.e. see the interaction it is not the best with turnarounds on github on tickets https://github.com/tensorflow/addons/issues/1305 or for community recurses (SIG?).
