### ISSUE TITLE
Link to TensorFlow roadmap is broken

### ISSUE THREAD

**Issue by guillaumekln** [tensorflow/community#206]
In https://www.tensorflow.org/community, the link "See product roadmap" at the end of the page is broken.

**Comment by bhack** [comment]
It Is broken also in https://github.com/tensorflow/tensorflow/blob/master/README.md#resources

But the main problem is that TF Roadmaps are quite useless and systematically outdated. See proposals in https://github.com/tensorflow/community/issues/29#issuecomment-550271413

**Comment by bhack** [comment]
We can close this

**Comment by bhack** [comment]
@ematejska We can close this

**Comment by ematejska** [comment]
Thanks for the contribution!
