### ISSUE TITLE
How do i connect with GSOC Mentors?

### ISSUE THREAD

**Issue by ayushmankumar7** [tensorflow/community#213]
# Community repo

HI, I am Ayushman Kumar, a GSoC 2020 aspirant. I am really struggling to connect myself with any mentor. I have joined the Gitter channel, mailed in the given email address but i did not get any response. If someone can help me connect with the mentor, i will be helped a lot. 
Thank you.

**Comment by yongtang** [comment]
@ayushmankumar7 I can help with I/O, audio/video, data format, or data streaming (like kafka) related topics in tensorflow for GSoC.

**Comment by ayushmankumar7** [comment]
I am looking forward to work on "Core Model Migration to TensorFlow 2.x (with TPUs!)". I had a few questions reguarding this project. If someone could help me clear my doubts, it would be really helpful for me.

**Comment by yongtang** [comment]
Don't know who is the mentor for `Core Model Migration to TensorFlow 2.x (with TPUs!)`, maybe you can send email to https://groups.google.com/a/tensorflow.org/forum/#!forum/developers

**Comment by ayushmankumar7** [comment]
Thank you so much for the help!

**Comment by pilgrm** [comment]
Hey, I recently came across Mesh RCNN after facebook released Pytorch3D, and actually also studied a research paper on MeshCNN(Both the Mesh Networks are quite different though). I want to work on that. So, where should I begin from.
My name is Gurlop, and I am suffering from a Mentor crisis as well!

**Comment by pilgrm** [comment]
Hi, I recently came across Mesh RCNN after facebook released Pytorch3D, and actually also studied a research paper on MeshCNN (Both the Mesh Networks are quite different though) for a seminar at college. I want to work on MeshRCNNs for GSOC. So, where should I begin? Please help me finding the right place to discuss this.
My name is Gurlop, and I am suffering from a Mentor crisis as well!

**Comment by Eshan-Agarwal** [comment]
@yongtang  I am interested in `Implement key research data in TFDS` , `New models + colab demos`, `Help migrate a TensorFlow library to TensorFlow 2.x` can you help me regarding these ?

**Comment by yongtang** [comment]
@Eshan-Agarwal Not very familiar with the topic in tfds, maybe @Conchylicultor or @rsepassi has more context with respect to this one?

**Comment by Eshan-Agarwal** [comment]
Ok so they are mentors for tfds or members ?

**Comment by yongtang** [comment]
@Eshan-Agarwal Please see https://github.com/tensorflow/datasets

**Comment by Eshan-Agarwal** [comment]
Yes , I am already contributing to tfds.

**Comment by Conchylicultor** [comment]
Thanks for reaching out, Eshan!
Looking forward to seeing your Google Summer of Code proposal!

**Comment by lazlozerv** [comment]
Hi @Conchylicultor, I am also interested in `New models + colab demos`,  `Core Model Migration to TensorFlow 2.x` and `High level TensorList API`.  What I should look to get familiar with these (mainly for TensorList API, as for the others I have already started to look the respective repos) ?

**Comment by ManishAradwad** [comment]
Hello @Conchylicultor , can I send you my first draft of proposal so that I can get your feedback on it?

**Comment by Avilad0** [comment]
Hey @yongtang  @Conchylicultor , Can you help me find the mentor for GSOC 2020 project   "Autograph and @tf.function High level TensorList API "

**Comment by uppalutkarsh** [comment]
Hi @yongtang @Conchylicultor , I am interested in "Implementation of implicit 3D representations in TensorFlow Graphics" project and, am currently facing difficulty contacting the mentor for the project. I'll appreciate any assistance regarding the issue.

**Comment by yongtang** [comment]
@Avilad0 @uppalutkarsh I don't know who is the mentor for those projects, but my recommendation is to send an email to tensorflow-developers google group (email list).

**Comment by uppalutkarsh** [comment]
@yongtang Thanks for the info.

**Comment by himanshu-dutta** [comment]
@Conchylicultor I would really love to work on the extension of datasets in TFDS and it would be a great help if I got your guidance for the same.

**Comment by Ankuraxz** [comment]
@Conchylicultor I am also interested in *New models + colab demos* and *Core Model Migration to TensorFlow 2.x* reaally looking forward for an opportunity like GSOC 2020
#213

**Comment by theadactyl** [comment]
Hi all! Now that we have the forum, I recommend you create a topic in the TensorFlow Forum to network with other GSOC participants: https://discuss.tensorflow.org/

**Comment by parthbagda211** [comment]
This is to bring to notice that in the Project " KerasCV: Object Detection API completion or Multi Modal model workflows" in there was no mention of the potential mentors. It would be great if the name of the potential mentors for this project is added.

Regards
