### ISSUE TITLE
Better Tensorboard Logging

### ISSUE THREAD

**Issue by chriskoups** [tensorflow/community#22]
Maybe that issue is only personal due to the nature of my problem.
I am training (using keras) in triple loops and I have the inner loop executed just 5 times. Even if I said the Tensorboard to log data every 100+ loops, it will log the data of each first time of the triple loop.

Full explanation:
I have 400 simulation experiments that have 1000 timestamps each. The training must reset its states each time that the simulation finishes and then the outer loops. Training happens mainly in inner loops so I have to set "inner loops - simulation number - external loops".
That will result in a really big training epochs, usually 5(inner) x 400(simulations) x 1000(outer epochs) = 2.000.000. The data logging is becoming really difficult because I would just like to have a log every 100 simulations? maybe even less but because the Tensorboard must note each time that the inner loop is called, I end up with 400.000 datalogs (each of 2-3MB, add up to 1TB per training!)
A work around (but messy) is to have a flag that I called every 100 simulation to enable the Tensorboard for that instant.

Proposed solution:
A frequency variable (at least in keras) that will actually count the number of epochs by counting the times that the callback is used. I will assume that this problem also imply to bigger networks that have hundreds inner loops but for them the problem can be solved by increasing the histogram_freq but my proposition is for a more general use.

**Comment by ewilderj** [comment]
Sorry, can you move this issue to the tensorflow/tensorflow project? It won't get attention in this project, "community" is for processes such as the RFCs and Special Interest Groups.
