### ISSUE TITLE
How to apply for google code in mentor 

### ISSUE THREAD

**Issue by technosier** [tensorflow/community#222]
# Community

Hi, I'm Tarun i almost searched every pages google how to be mentor in such organization. 
I have many questions regarding it
How to apply, 
How to find them, 
What is the last dates, 
Where do we find information about them etc.

**Comment by bhack** [comment]
I don't know if the Tensorflow policy accept external mentors in CODE-IN and GSOC programs. /cc @dynamicwebpaige

**Comment by lsdmen23** [comment]
Great

**Comment by theadactyl** [comment]
Hi all! Now that we have the forum, I recommend you create a topic in the TensorFlow Forum to network with other GSOC participants: https://discuss.tensorflow.org/
