### ISSUE TITLE
Create process for (or guidance around) creation of new community properties

### ISSUE THREAD

**Issue by theadactyl** [tensorflow/community#225]
# Community repo

The only issues you should file here concern the community's documentation or processes.

All other bugs should be filed on the appropriate repo, questions directed to the various email groups, or if it's a "how-to" question, StackOverflow.

**Comment by bhack** [comment]
Do you have the resource, as a team, to allocate a repository scan 2/5 minutes at day? 
Cause we had regular outdated RFC without a negative or positive outcome , never triaged issues, trivial PR pending by months etc.

**Comment by ematejska** [comment]
Sorry about any delays.  The RFC PRs are scanned on a regular basis.  Currently there are 15 outstanding ones and there are some old ones.  I'll investigate if some of them can be moved along.  When the RFC is moved along, do you think that communications could be improved there?  For example, results from the Design review meetings, etc.

**Comment by theadactyl** [comment]
@bhack can we keep this issue on-topic for creation of community properties?

**Comment by bhack** [comment]
@theadactyl Do you mean that this is a meta ticket to collect all the community properties? Or are you restricting the whole repository ISSUE to "community's documentation or processes"?
If the case is the first one ok. 
Instead if the case is last one I think is pertinent to know if we could rely on this repository.

**Comment by theadactyl** [comment]
Just this issue -- I want to make sure we stick to one topic per issue so we can better organize feedback and responses

**Comment by bhack** [comment]
Ok about this thread the first point that i want to understand is how the new community properties proposals will be evaluated in this hypothetical process:

- There will be a consensus process between SIG representative (SIG representative can upvote on an issue, unanimity, majority etc..)?
- Or they will be evaluated by a internal company process/thread and we will be only exposed to a short final rationale of the outcome?

**Comment by bhack** [comment]
Also to be more inclusive Is there Github team with all the SIG official maintainers to mention? Cause I don't think that they are regularly watching this repo.

**Comment by theadactyl** [comment]
Not that I know of, but that could be helpful. Can you file an issue?

**Comment by terrytangyuan** [comment]
@bhack @theadactyl I don't think there's a mega team for all the SIG maintainers yet. Though there are separate GitHub teams for different SIGs and each team is watching both their responsible SIG repo as well as this community repo.

**Comment by bhack** [comment]
I've opened it https://github.com/tensorflow/community/issues/227. 
But if we are sure that they are already actively watching this REPO you can close it.
