### ISSUE TITLE
Community repository minimum maintenance

### ISSUE THREAD

**Issue by bhack** [tensorflow/community#226]
Can we expect to have a regular maintenance of this low traffic community repository? 

* Many RFCs go regularly out of the comment deadline and we don't know the public status of the process for months.
* Many very trivial fixes on docs are not merged or if approved we need to wait for months.
* Many sparse topics issues like Gsoc/Code in are not closed or redirected to the right place. 

I think that a regular 10 minutes check one or two times at weeks it is enough triage and maintain this repo in an healty and useful status as is the many communication channel between the internal team and the Tensorflow community.

**Comment by bhack** [comment]
To improve the public communication It could be nice if the implementation start after the RFC it is public approved (merged) https://github.com/tensorflow/community/pull/182#issuecomment-613573220

**Comment by mihaimaruseac** [comment]
Agree, but note that that commit you mention landed **after** the RFC approval, not before.

**Comment by ematejska** [comment]
The problem here was with the process (I run the RFC process nowadays and take full responsibility.) The design was was reviewed but the communication was not good afterwards.  Thank you for this feedback.

**Comment by bhack** [comment]
@mihaimaruseac I don't see this in our governance https://github.com/tensorflow/community/blob/master/governance/rfc-admin-guide.md#rfc-acceptance-process.
You can always open a PR to change our governance.

**Comment by bhack** [comment]
@ematejska I am glad that you are the owner of the RFC. I hope that we could improve the labeling governance after the comment public deadline.

**Comment by bhack** [comment]
@mihaimaruseac Don't take it as personal by downvoting. You are internal and sometimes you cannot understand that we are totally unaware of what will happen with respect to your internal threads. As a community we only know what is public.

**Comment by bhack** [comment]
Can you give a pass to noise tickets?

**Comment by bhack** [comment]
@ematejska I think that we could evaluate to close almost all the open issues in the repo.

**Comment by ematejska** [comment]
@bhack @theadactyl and I have started to go through these on a periodic cadence.  We should get to these issues early next week at the latest.

**Comment by bhack** [comment]
Thanks

**Comment by theadactyl** [comment]
Got to the issues! We are working steadily on the RFC backlog as well, so closing this issue.
