### ISSUE TITLE
Create a Github team for SIG mantainers

### ISSUE THREAD

**Issue by bhack** [tensorflow/community#227]
It could be helpful to quickly involve official SIG maintainers in general purpose SIGs threads/decisions.

https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams

**Comment by terrytangyuan** [comment]
Another suggestion is that SIG maintainers should be able to merge PRs that modify the folders that we maintain. This would avoid situation like in https://github.com/tensorflow/community/pull/211 where the PR has not been merged yet (after 2 weeks at the time of writing).

**Comment by bhack** [comment]
Mhh. It Is not explicit but I don't think they could be classified as maintainer in this repo: https://github.com/tensorflow/community/blob/master/governance/code-and-collaboration.md#maintainers

**Comment by terrytangyuan** [comment]
Perhaps we could set up something similar to what's done in Kubernetes-related projects (e.g. Kubeflow) which use [prow](https://prow.k8s.io/command-help) and `OWNERS` file so that changes to sub-folders can be approved/merged by users specified in the `OWNERS` file in the corresponding sub-folder.

**Comment by bhack** [comment]
What I meant Is that our ownership governance was about review not merge. Ownership and write power is not the same role in our governance:
https://github.com/tensorflow/community/blob/master/CODEOWNERS

**Comment by terrytangyuan** [comment]
Oh I see what you mean now. Anyways, the more the community (especially SIG maintainers) can get involved and help move things forward quickly, the better.

**Comment by bhack** [comment]
@terrytangyuan My opinon Is that with the right level of trust could be ok. But to achieve this we need to explict this interpretation somewhere in the governance folder and that the community team agree about this policy.
