### ISSUE TITLE
Switching default [float | int] types in Tensorflow 2.0

### ISSUE THREAD

**Issue by awav** [tensorflow/community#23]
Hello everyone,

Not be able to switch between default types has been an issue for such projects like [GPflow](https://github.com/GPflow/GPflow/) since the beginning of the TensorFlow. I guess a way of changing default types in TensorFlow will make a lot of things easier.

That question was raised before, e.g. https://github.com/tensorflow/tensorflow/issues/9781, where usually maintainers argued that GPU is much faster on float32, default type cannot (should not) be changed because of backwards compatibility reasons. The thing is that precision is very important for such operations like cholesky, solvers and etc. If project uses only such operations, you have to specify type everywhere, it gets even worse when you start using other frameworks or small libraries which follow standard type settings and sometimes they become useless. The policy of "changing types locally will solve your problems" becomes cumbersome.

It would be great to have methods `tf.set_default_float` and `tf.set_default_int` in TensorFlow 2.0 and I believe that such a small change will make TensorFlow a bit more appealing.

**Comment by ewilderj** [comment]
Please could you move this issue to tensorflow/tensorflow? It won't get any attention in tensorflow/community ... or raise the issue on discuss@tensorflow.org.
