### ISSUE TITLE
/posenet/ios/: Unresolved identifier 'CoreMLDelegate'

### ISSUE THREAD

**Issue by dwarfKing777** [tensorflow/community#248]
# Community repo
I loaded iOS project to Xcode from below location:
examples/lite/examples/posenet/ios/

I am getting below error on building the project:
Use of unresolved identifier 'CoreMLDelegate'

**Comment by TVI-BIZ** [comment]
same here. copy from official repo

**Comment by di-d6** [comment]
> same here. copy from official repo

**Comment by TVI-BIZ** [comment]
I solve it. The solution founded in TF site.
the problem in pod file 
find the string: pod 'TensorFlowLiteSwift/CoreML', '~> 0.0.1-nightly' 
and change it to pod 'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML'] - it solve all you problem.
if you also have problem with MetalDelegate 
'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML','Metal'] 
not sure about it is exactly Metal or not, but you get the point how to solve it
