### ISSUE TITLE
How MLIR relates to TF-Lite, GPU delegates, NNAPI?

### ISSUE THREAD

**Issue by peter197321** [tensorflow/community#251]
As a current user of TensorFlow-lite where NNAPI or GPU delegate are used to execute an inference on accelerated IP block then I have outlook question if this MLIR can replace or live side-by-side to this now existing mechanism (NNAPI, delegates or MLIR is about to replace those approaches?

**Comment by bhack** [comment]
I think nobody here will reply to your question. It Is better that you close this and post this question at https://groups.google.com/a/tensorflow.org/forum/m/#!forum/mlir.

You could be also interested in https://github.com/tensorflow/runtime/issues/6
