### ISSUE TITLE
Lack of proper documentation to remove tf.contrib module from V1's code 

### ISSUE THREAD

**Issue by ishdutt** [tensorflow/community#259]
# Community repo

There is no effective guide/documentation showing how to get rid of the `tf.contrib`'s modules of V1 and their alternatives in V2 of Tensorflow. The only page that exists is this RFC: [Sunsetting contrib](https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md) which is pretty outdated and needs modification. It has many blank slots,**?** indicating that their future destination was not confirmed at the time this RFC was being drafted.

Can we have a dedicated page for the alternatives of `tf.contrib` modules in V2 and the location of the old modules which are retained in V2?
I'm also willing to contribute to the TensorFlow community :)
Thanks!

**Comment by theadactyl** [comment]
Hi ishdutt, apologies for the late response. This would be better addressed by the Core or Website teams, as the community team doesn't have granular information about the contrib turndown. Will pass this feedback along in case it's still impacting contrib users.
