### ISSUE TITLE
Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only

### ISSUE THREAD

**Issue by BCoxford** [tensorflow/community#264]
I am receiving this error message when running my tensorflow program.

Error Message: tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: Invoking GPU asm compilation is supported on Cuda non-Windows platforms only
Relying on driver to perform ptx compilation.
Modify $PATH to customize ptxas location.
This message will be only logged once.

I do not believe it is an issue with my program as I have been searching around trying to find a solution and as stated in [#33375](https://github.com/tensorflow/tensorflow/issues/33375), this seem to be a common issue with the program itself. I have tried a workaround which was suggested by system linking the folder but this has not resolved the issue.

I am using:

Tensorflow 2.2.0 with Python 3.8, CUDA 10.1 and Cudnn 7.6 for Cuda 10.1.

Please let me know if you need any more information.

Kind regards,

Ben.

**Comment by FilloFolla** [comment]
Gasp. I have the same problem

**Comment by donglinz** [comment]
same

**Comment by xielongze** [comment]
same problem with tf2.1.0, python 3.7.0

**Comment by IIEliteIISquady** [comment]
I've had to reinstall it and have followed a tutorial using older compatible versions and it worked perfectly fine.

**Comment by Xperiencee** [comment]
> I've had to reinstall it and have followed a tutorial using older compatible versions and it worked perfectly fine.

Can you provide the link to that tutorial and the compatible version that worked for you please
?

**Comment by dreamee-git** [comment]
same problem with Tensorflow 2.3.1, Python 3.7.9, cuda 10.1, cudnn 7.6.5 on Windows 10 Enterprise

**Comment by BCoxford** [comment]
They’ve done an update since I posted this error and now there is a compatible version for Python 3.8. I’ll see how it goes and will respond if I get it to work.

**Comment by Miles345** [comment]
Have the same problem. It is using the gpu after the message but CPU is the bottleneck.

**Comment by xielongze** [comment]
> Have the same problem. It is using the gpu after the message but CPU is the bottleneck.

I've encountered the same problem but then I found out it was the data augmentation that slowed the process down. After I deleted that part of the code, the CPU is no longer the bottleneck. Don't know whether this is helpful or not.

**Comment by ronnie-bit** [comment]
Hi

The clear answer is that CUDA 10.1 does not support Tensorflow 2.2.0 and above versions
rather you have to install tensorflow 2.1.4 with other specific compatible combinations

first you have to uninstall the existing following packages

now copy n paste following one by one in command prompt

pip install tensorflow==2.1.4 tensorflow-gpu==2.1.4 tensorflow-estimator==2.1.0 tensorflow-gpu-estimator==2.1.0 tensorboard==2.1.1 tf-models-official==2.1.0.dev2

pip install opencv-python==4.5.1.48 opencv-contrib-python==4.5.1.48

pip install numpy==1.18.5

pip install keras==2.3.1

python -c "import tensorflow as tf;print(tf.reduce_sum(tf.random.normal([1000, 1000])))"

these combination worked for me and hope it will work for you also.

Win10
Python==3.7.10
CUDA - 10.1
CuDNN - 7.6.5
GPU - NVIDIA GTX 1660ti (in my case)

reference links

[https://www.tensorflow.org/install/source_windows](url)
[https://docs.floydhub.com/guides/environments/](url)

**Comment by aeromag00** [comment]
It's same my case. I use below version.
#CUDA==10.1u2
#cuDNN==7.6.5
#tensorflow-gpu==2.3.0
