### ISSUE TITLE
import problem hope to solving it

### ISSUE THREAD

**Issue by alexjunyue** [tensorflow/community#272]
>>> import tensorflow
Traceback (most recent call last):
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /Users/alexjunyuexuli/anaconda3/envs/tensorflow/lib/python3.7/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

how to deal with this problem? thanks so much!

alexjunyue

**Comment by mihaimaruseac** [comment]
This should be opened in https://github.com/tensorflow/tensorflow as it seems to be related to the code there. When you open it there, can you please fill in the issue template (macos version, TF version, pip version, building from source or installing from pip or from conda?). Also, when you open the issue there, can you also provide the outputs of

```
python -vvv -c "import tensorflow as tf" &> log.txt
```

by attaching `log.txt`?

You can mention me in the issue when you create it so I can look into it and all of the details.

At the moment, this looks like either a symbol leakage from the build toolchain or something related to the setup you are using (e.g., ABI incompatibility)

**Comment by alexjunyue** [comment]
thanks for your response feedback infos.
it 's copying after installed i's infos.
Installing collected packages: tensorflow-estimator, tensorflow
Successfully installed tensorflow-2.0.1 tensorflow-estimator-2.0.1

1: i have used pip to installed it
2:macos:10.10.5
3:tf-version==2.0.1
4:pip-version==pip 20.1.1 from /anaconda3/lib/python3.6/site-packages/pip (python 3.6)

please  checking my response . please help me to thanks so much.if you have any questions ,pleas feel free to help .thanks again.
have good time
alexjunyue

**Comment by alexjunyue** [comment]
>>> import tensorflow as tf
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/anaconda3/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/anaconda3/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
  Referenced from: /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib
  Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
 in /anaconda3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>> 
this log is error infos.

**Comment by mihaimaruseac** [comment]
Please run 
```
python -vvv -c "import tensorflow as tf" &> log.txt
```

and **atach** `log.txt`

**Comment by alexjunyue** [comment]
alexjunyuexulis-MacBook-Pro:~ alexjunyuexuli$ vim log.txt

import _frozen_importlib # frozen
import _imp # builtin
import sys # builtin
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
# /anaconda3/lib/python3.6/encodings/__pycache__/__init__.cpython-36.pyc matches /anaconda3/lib/python3.6/encodings/__init__.py
# code object from '/anaconda3/lib/python3.6/encodings/__pycache__/__init__.cpython-36.pyc'
# trying /anaconda3/lib/python3.6/codecs.cpython-36m-darwin.so
# trying /anaconda3/lib/python3.6/codecs.abi3.so
"log.txt" 10235L, 359323C

Are these details  your request infos?
if it is ok ,please checking it.
thanks so mush.

**Comment by alexjunyue** [comment]
>i have attached my log.txt for you .
please checking .
thanks so much !

[log.txt](https://github.com/tensorflow/community/files/4998618/log.txt)

**Comment by mihaimaruseac** [comment]
What is the output of `python -c "import imp"`?

**Comment by mihaimaruseac** [comment]
Also, what is the output of `pip list`?

**Comment by alexjunyue** [comment]
it is pip list's infos.

alexjunyuexulis-MacBook-Pro:~ alexjunyuexuli$ pip list
Package                            Version
---------------------------------- ----------------------
absl-py                            0.9.0
alabaster                          0.7.10
anaconda-client                    1.6.14
anaconda-navigator                 1.8.7
anaconda-project                   0.8.2
appnope                            0.1.0
appscript                          1.0.1
asn1crypto                         0.24.0
astor                              0.8.1
astroid                            1.6.3
astropy                            3.0.2
attrs                              18.1.0
Babel                              2.5.3
backcall                           0.1.0
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.6.0
bitarray                           0.8.1
bkcharts                           0.2
blaze                              0.11.3
bleach                             2.1.3
bokeh                              0.12.16
boto                               2.48.0
Bottleneck                         1.2.1
cachetools                         4.1.1
catboost                           0.23.2
certifi                            2020.6.20
cffi                               1.11.5
chardet                            3.0.4
click                              6.7
cloudpickle                        0.5.3
clyent                             1.2.2
cmake                              3.18.0
colorama                           0.3.9
conda                              4.8.3
conda-build                        3.10.5
conda-package-handling             1.7.0+0.g7c4a471.dirty
conda-verify                       2.0.0
contextlib2                        0.5.5
cryptography                       2.9.2
cycler                             0.10.0
Cython                             0.28.2
cytoolz                            0.9.0.1
dask                               0.17.5
datashape                          0.5.4
decorator                          4.3.0
distributed                        1.21.8
docutils                           0.14
entrypoints                        0.2.3
enum34                             1.1.10
et-xmlfile                         1.0.1
fastcache                          1.0.2
filelock                           3.0.4
Flask                              1.0.2
Flask-Cors                         3.0.4
gast                               0.2.2
gevent                             1.3.0
glob2                              0.6
gmpy2                              2.0.8
google-auth                        1.19.2
google-auth-oauthlib               0.4.1
google-pasta                       0.2.0
graphviz                           0.14.1
greenlet                           0.4.13
grpcio                             1.30.0
h5py                               2.7.1
heapdict                           1.0.0
html5lib                           1.0.1
idna                               2.6
imageio                            2.3.0
imagesize                          1.0.0
importlib-metadata                 1.7.0
importlib-resources                3.0.0
ipykernel                          4.8.2
ipython                            6.4.0
ipython-genutils                   0.2.0
ipywidgets                         7.2.1
isort                              4.3.4
itsdangerous                       0.24
jdcal                              1.4
jedi                               0.12.0
Jinja2                             2.10
jsonschema                         2.6.0
jupyter                            1.0.0
jupyter-client                     5.2.3
jupyter-console                    5.2.0
jupyter-core                       4.4.0
jupyterlab                         0.32.1
jupyterlab-launcher                0.10.5
Keras-Applications                 1.0.8
Keras-Preprocessing                1.1.2
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
lightgbm                           2.3.1
llvmlite                           0.23.1
locket                             0.2.0
lxml                               4.2.1
Markdown                           3.2.2
MarkupSafe                         1.0
matplotlib                         2.2.2
mccabe                             0.6.1
mistune                            0.8.3
mkl-fft                            1.0.0
mkl-random                         1.0.1
more-itertools                     4.1.0
mpmath                             1.0.0
msgpack-python                     0.5.6
multipledispatch                   0.5.0
navigator-updater                  0.2.1
nbconvert                          5.3.1
nbformat                           4.4.0
netaddr                            0.8.0
networkx                           2.1
nltk                               3.3
nose                               1.3.7
notebook                           5.5.0
numba                              0.38.0
numexpr                            2.6.5
numpy                              1.19.1
numpydoc                           0.8.0
oauthlib                           3.1.0
odo                                0.5.1
olefile                            0.45.1
openpyxl                           2.5.3
opt-einsum                         3.3.0
packaging                          17.1
pandas                             1.0.5
pandocfilters                      1.4.2
parso                              0.2.0
partd                              0.3.8
path.py                            11.0.1
pathlib2                           2.3.2
patsy                              0.5.0
pep8                               1.7.1
pexpect                            4.5.0
pickleshare                        0.7.4
Pillow                             5.1.0
pip                                20.1.1
pkginfo                            1.4.2
plotly                             4.9.0
pluggy                             0.6.0
ply                                3.11
prompt-toolkit                     1.0.15
protobuf                           3.12.2
psutil                             5.4.5
ptyprocess                         0.5.2
py                                 1.5.3
pyasn1                             0.4.8
pyasn1-modules                     0.2.8
pycodestyle                        2.4.0
pycosat                            0.6.3
pycparser                          2.18
pycrypto                           2.6.1
pycurl                             7.43.0.5
pyflakes                           1.6.0
Pygments                           2.2.0
pylint                             1.8.4
pyodbc                             4.0.23
pyOpenSSL                          18.0.0
pyparsing                          2.2.0
PySocks                            1.6.8
pytest                             3.5.1
pytest-arraydiff                   0.2
pytest-astropy                     0.3.0
pytest-doctestplus                 0.1.3
pytest-openfiles                   0.3.0
pytest-remotedata                  0.2.1
python-dateutil                    2.7.3
pytz                               2018.4
PyWavelets                         0.5.2
PyYAML                             3.12
pyzmq                              17.0.0
QtAwesome                          0.4.4
qtconsole                          4.3.1
QtPy                               1.4.1
requests                           2.24.0
requests-oauthlib                  1.3.0
retrying                           1.3.3
rope                               0.10.7
rsa                                4.6
ruamel-yaml                        0.15.35
scikit-image                       0.13.1
scikit-learn                       0.19.1
scipy                              1.1.0
seaborn                            0.8.1
Send2Trash                         1.5.0
setuptools                         49.2.0
simplegeneric                      0.8.1
simplejson                         3.17.2
singledispatch                     3.4.0.3
six                                1.11.0
sklearn                            0.0
snowballstemmer                    1.2.1
sortedcollections                  0.6.1
sortedcontainers                   1.5.10
Sphinx                             1.7.4
sphinxcontrib-websupport           1.0.1
spyder                             3.2.8
SQLAlchemy                         1.2.7
statsmodels                        0.9.0
sympy                              1.1.1
tables                             3.4.3
TBB                                0.1
tblib                              1.3.2
tensorboard                        2.0.2
tensorflow                         2.0.1
tensorflow-estimator               2.0.1
termcolor                          1.1.0
terminado                          0.8.1
testpath                           0.3.1
toolz                              0.9.0
tornado                            5.0.2
tqdm                               4.47.0
traitlets                          4.3.2
transforms                         0.1
typing                             3.6.4
unicodecsv                         0.14.1
urllib3                            1.22
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.31.1
widgetsnbextension                 3.2.1
wrapt                              1.12.1
xgboost                            0.90
xlrd                               1.1.0
XlsxWriter                         1.0.4
xlwings                            0.11.8
xlwt                               1.2.0
zict                               0.1.3
zipp                               3.1.0
alexjunyuexulis-MacBook-Pro:~ alexjunyuexuli$

**Comment by alexjunyue** [comment]
alexjunyuexulis-MacBook-Pro:~ alexjunyuexuli$ python -c "import imp"
alexjunyuexulis-MacBook-Pro:~ alexjunyuexuli$ 

i used your request (python -c "import imp")command to enter it ,nothing response .
please checking .

thank you so much!

**Comment by mihaimaruseac** [comment]
The `import imp` test looks ok. The `pip list` looks very big. Can you try to create a new virtualenvironment and install `tensorflow` into that one? If possible, can you use TF 2.3 instead of TF 2.0?
