### ISSUE TITLE
Use my model in a webpage

### ISSUE THREAD

**Issue by GialiBoM** [tensorflow/community#279]
I have created an object recognition model, using Colab where I can load an image from my drive and the model recognizes the object from my object
I saved the model in **.json** with its related **.bin** sheets
But I also have the same model saved in **.py .ipynb .h5**

I would like to apply this acknowledgment template on my website, in JS

I've been trying to find out online for days, or reading this link
https://www.tensorflow.org/js/tutorials/conversion/import_keras
I also tried the code shown here
but I still can't find a solution

**Comment by hodovani** [comment]
@GialiBoM could you please clarify your problem?

**Comment by preyash2047** [comment]
> @GialiBoM could you please clarify your problem?

I am also having  the issue, unable to load my .json model using tf.loadModel("path to model")

It is showing  this error "tf.loadModel" is not function 

How to load keras based model in js?

**Comment by hodovani** [comment]
@preyash2047 thanks for your report. 

> How to load keras based model in js?

[Here](https://github.com/tensorflow/tfjs-examples/tree/21d2eb88ea444f3056b887c57c07dd8ce924faf0/mnist-transfer-cnn) is a good example where you can find how to import your model. Could you please run it locally and confirm that `loadLayersModel ` works for you in this example. [Here](https://github.com/tensorflow/tfjs-examples/blob/21d2eb88ea444f3056b887c57c07dd8ce924faf0/mnist-transfer-cnn/loader.js#L43) is a place where we load a model. 

> It is showing this error "tf.loadModel" is not function

Could you confirm please that you imported TensorFlow correct?

Could you also share a `.json` file or an example of code that run `tf.loadLayersModel`?

Thanks.

**Comment by preyash2047** [comment]
Thank you for Quick reply,

i found error: "Uncaught TypeError: Failed to resolve module specifier
"@tensorflow/tfjs". Relative references must start with either "/", "./",
or "../"."
I am googling this for two days still not find the solution for this,
how to solve above mentioned error


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
22/09/20,
11:26:10 pm

**Comment by GialiBoM** [comment]
> @GialiBoM could you please clarify your problem?

Sorry if I answer just now
I leave you my exact question, with reference code here
https://stackoverflow.com/questions/63703062/load-object-recognition-model-created-in-colab-in-a-javascript-web-page

**Comment by GialiBoM** [comment]
@hodovani Sorry if I answer just now
I leave you my exact question, with reference code here
https://stackoverflow.com/questions/63703062/load-object-recognition-model-created-in-colab-in-a-javascript-web-page

**Comment by preyash2047** [comment]
Thank you,

I have just solved the error, with this simple code:
https://github.com/preyash2047/preyash2047.github.io/blob/master/home/test.html
which is hosted on https://preyash2047.github.io/home/test


thank you



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
23/09/20,
05:49:40 pm

**Comment by preyash2047** [comment]
Hey, 
I have done project on handwritten text recognition and implemented using tensorflow.js, and I have implemented this on 25th Sep 2020, so everything will work for you also
check out my project which is live at https://preyash2047.github.io/textdetection.html
Repo: https://github.com/preyash2047/preyash2047.github.io/blob/master/textdetection.html

Note: use console to know the status of model downloading and background process
