### ISSUE TITLE
Adopt contributor covenant

### ISSUE THREAD

**Issue by bhack** [tensorflow/community#28]
Can we adopt the [contributor covenant](https://www.contributor-covenant.org/) in Tensorflow?

**Comment by martinwicke** [comment]
TensorFlow's code of conduct is an adaptation the contributor covenant (see https://github.com/tensorflow/community/blob/master/CODE_OF_CONDUCT.md).

**Comment by bhack** [comment]
We are not in https://www.contributor-covenant.org/adopters

**Comment by CoralineAda** [comment]
Every community is free (and actually encouraged) to adapt the Contributor Covenant to their particular needs. From what I read, the Tensorflow CoC is true to the spirit of the original. I wouldn't have an issue with adding the project to the list of adopters. Instructions for doing so can be found here: https://github.com/ContributorCovenant/contributor_covenant#adding-a-project-to-the-list-of-adopters

**Comment by bhack** [comment]
Thanks. @martinwicke can I open a PR on that repository?

**Comment by ewilderj** [comment]
@bhack sounds good!

**Comment by bhack** [comment]
Done witih https://github.com/ContributorCovenant/contributor_covenant/pull/622

**Comment by CoralineAda** [comment]
I went ahead and added the project to the Featured Adopters list on the main page too. 🖤

**Comment by ewilderj** [comment]
Thank you @bhack @CoralineAda !
