### ISSUE TITLE
Broken link for "TF API Owners"

### ISSUE THREAD

**Issue by lithuak** [tensorflow/community#280]
[This "Overview" section](https://github.com/tensorflow/community/blob/master/governance/api-reviews.md#overview) contains the broken link: [TF API Owners](https://github.com/orgs/tensorflow/teams/api-owners)

**Comment by ematejska** [comment]
This link seems works for me (at least now).  Please re-open if that still doesn't work.

**Comment by adriangb** [comment]
It's broken. Doesn't work for me. Maybe it's an internal link?

**Comment by allenlavoie** [comment]
It's possible the visibility for that team is set incorrectly (only people in the TF github org?). It doesn't look like a "secret" team to me; it's listed under visible teams. Opening the link in an incognito window does ask me to sign in, which seems wrong.

**Comment by adriangb** [comment]
If you can't get to it in an incognito window, then it's not a public link. I'm seeing the same thing in incognito.

**Comment by bhack** [comment]
@allenlavoie Probably the visibility concept is different in Github. See https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/about-teams#team-visibility

**Comment by allenlavoie** [comment]
Ah, good catch "Visible teams can be viewed and @mentioned by every organization member."; so the exception indicates the rule that non-organization members can't view them. We should probably remove the link and find another way to communicate the information.

@ematejska I don't think anyone else can re-open bugs here.

**Comment by bhack** [comment]
I think also @theadactyl can reopen it

**Comment by bhack** [comment]
I propose a solution with https://github.com/tensorflow/community/pull/379

**Comment by theadactyl** [comment]
cc @ematejska can you take another look?
