### ISSUE TITLE
ERROR subscribe to tensorflow newsletter

### ISSUE THREAD

**Issue by stromal** [tensorflow/community#294]
https://services.google.com/fb/forms/tensorflow/
"Thank you for your interest. The form you are trying to access has either expired or reached its maximum registration limit."

With and without  google extensions.

![tf newsleeter](https://user-images.githubusercontent.com/19979901/94677118-49f5b200-0314-11eb-9a6d-b16e6aef8498.PNG)

**Comment by Pointdexter99** [comment]
It's working fine for now.

**Comment by stromal** [comment]
The signup worked (hopefully), I haven't received a confirmation mail even after 5 min. 
This is how the site looks like just after the sign up.
![2022 02 01 tensorflow email signup](https://user-images.githubusercontent.com/19979901/151996941-b939f69f-c4e0-4afc-a0f9-18ae404dfb11.JPG)

**Comment by theadactyl** [comment]
I'm also getting the broken image -- no confirmation email might be by design, but I'm checking with newsletter team.

**Comment by stromal** [comment]
Please update this thread if you get to know anything. This is quiet problematic because I would love to be more involved with the core team's vision.

**Comment by kristenrq** [comment]
@stromal Hello! That is correct, viewing that page is confirmation of signup;  there is no additional email.

That image _is_ broken, however. Thank you for reporting!

**Comment by stromal** [comment]
I still haven't received a single newsletter email from TensorFlow. Can anyone look in to this? Is there anyone who receives any newsletter emails?

**Comment by Sarah-whv** [comment]
Yes I receive newsletter Emails. No confirmation E-Mail.
Two weeks after signing up I receive a Newsletter on 31.05.2023

**Comment by theadactyl** [comment]
We have a new form live here that should be working: https://www.tensorflow.org/subscribe
