### ISSUE TITLE
Tensorflow TypeError

### ISSUE THREAD

**Issue by sourabh-st** [tensorflow/community#305]
`import tensorflow.keras as tf
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

mnist = tf.datasets.mnist
(x_train,y_train),(x_test,y_test ) = mnist.load_data()
print(len(x_train))
plt.imshow(x_train[4],cmap='gray')
plt.show()

#Creating the Model

model = tf.models.Sequential()

#Adding the Layers
model.add(Flatten())
model.add(Dense(784,activation='relu'))  #784= 28X28 ##Hidden Layers
model.add(Dense(10,activation='softmax'))  #Output Layer
`

Error: 
TypeError                                 Traceback (most recent call last)
<ipython-input-13-354dab556e38> in <module>
      4 
      5 #Adding the Layers
----> 6 model.add(Flatten())
      7 model.add(Dense(784,activation='relu'))  #784= 28X28 ##Hidden Layers
      8 model.add(Dense(10,activation='softmax'))  #Output Layer

~/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py in add(self, layer)
    180       raise TypeError('The added layer must be '
    181                       'an instance of class Layer. '
--> 182                       'Found: ' + str(layer))
    183 
    184     tf_utils.assert_no_legacy_layers([layer])

TypeError: The added layer must be an instance of class Layer. Found: <keras.layers.core.Flatten object at 0x7fb776c2a8d0>

**Comment by adityasaini70** [comment]
You're essentially adding a Keras layer to a _purely_ Tensorflow based model which results in the error. Since you've already done
```
from keras.models import Sequential
```
at the top. So just change 
```
model = tf.models.Sequential()
```
to 
```
model = Sequential()
```

**Comment by swad007** [comment]
import tensorflow.keras as tf
import matplotlib.pyplot as plt
from keras.models import Sequential
from keras.layers import Conv2D
from keras.layers import MaxPooling2D
from keras.layers import Flatten
from keras.layers import Dense

mnist = tf.datasets.mnist
(x_train,y_train),(x_test,y_test ) = mnist.load_data()
print(len(x_train))
plt.imshow(x_train[4],cmap='gray')
plt.show()

#Creating the Model

model = tf.models.Sequential()

#Adding the Layers
model.add(Flatten())
model.add(Dense(784,activation='relu')) #784= 28X28 ##Hidden Layers
model.add(Dense(10,activation='softmax')) #Output Layer

#you have by mistakely added an apostrophy (puntuation) ahead of import tensorflow.keras as tf.
