### ISSUE TITLE
AttributeError: 'function' object has no attribute 'Tokenizer'

### ISSUE THREAD

**Issue by ylzzz** [tensorflow/community#320]
Traceback (most recent call last):
  File "E:/practice/python/2text.py", line 72, in <module>
    tokenizer = tfds.features.text.Tokenizer()
AttributeError: 'function' object has no attribute 'Tokenizer'

ps：Can someone please tell me how to solve this problem, I used the demo in the tensorflow document, but an error was reported in this place？

**Comment by Pointdexter99** [comment]
Tokenizer() isn't an attribute of tfds.features.text API it's  an attribute of tf.keras.preprocessing.text. Ex: tf.keras.preprocessing.text.Tokenizer(
    num_words=None, filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n', lower=True,
    split=' ', char_level=False, oov_token=None, document_count=0, **kwargs
)

I might be wrong, but this was what i found to help you out.
