### ISSUE TITLE
TypeError in CODEOWNERS document

### ISSUE THREAD

**Issue by Eatingbiu** [tensorflow/community#321]
# Community repo

The only issues you should file here concern the community's documentation or processes.

All other bugs should be filed on the appropriate repo, questions directed to the various email groups, or if it's a "how-to" question, StackOverflow.

TensorFlow/Community/CODEOWNERS
line10：
username "angersson" is supposed to be "angerson".

**Comment by terrytangyuan** [comment]
@Eatingbiu Thanks for reporting. I've submitted https://github.com/tensorflow/community/pull/332 to fix this.

**Comment by Eatingbiu** [comment]
@terrytangyuan Thanks!
