### ISSUE TITLE
Framework class error

### ISSUE THREAD

**Issue by daspranab** [tensorflow/community#322]
Tensorflow attribute placeholder is giving rise to error. However, when changing to Variable, it causes a framework class to break. A detailed step to reproduce on a laptop with a graphics card and tensorflow-gpu installed is described here: https://github.com/tensorflow/tensorflow/issues/44641#issuecomment-724490292. However, I am asked to repro the problem on Colab that will not resolve the issue.

**Comment by theadactyl** [comment]
We don't offer technical support on this repository. I recommend you create a topic in the TensorFlow Forum: https://discuss.tensorflow.org/
