### ISSUE TITLE
The error was: SyntaxError: Unexpected token < in JSON at position 6

### ISSUE THREAD

**Issue by YuriyTigiev** [tensorflow/community#329]
I  can't upload the ipynb files to anaconda from (https://github.com/tensorflow/docs/tree/master/site/en/r1/tutorials/keras
)

Any upload files return an error "The error was: SyntaxError: Unexpected token < in JSON at position 6"

https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/keras/basic_classification.ipynb
![image](https://user-images.githubusercontent.com/22752322/99190961-11eee500-2783-11eb-819e-3a65aa640919.png)

**Comment by theadactyl** [comment]
We don't offer technical support on this repository. I recommend you create a topic in the TensorFlow Forum: https://discuss.tensorflow.org/
