### ISSUE TITLE
I can't run my models on object detection for Android

### ISSUE THREAD

**Issue by GustavoMSevero** [tensorflow/community#330]
Hi guys!
I'm trying to develop an app to recongnize 2 kind of images, but i'm using models i have trained on Teachable Machine and put them in assets folder and nothing, nothing is detected kkkkkkk
It's been two weeks i'm looking for videos in youtube, archives in the internet trying to find out what's happing and to know why tflite package doesn't exists and nothing too. So, if anyone could help me, i'll be totally greatful.

If you want my models or the photos, just let me know.

Since now, thank you so much for your attention.
gustavo@gapps.com.br

**Comment by theadactyl** [comment]
We don't offer technical support on this repository. I recommend you create a topic in the TensorFlow Forum: https://discuss.tensorflow.org/
