### ISSUE TITLE
No alternative for tf.contrib.graph_editor ?

### ISSUE THREAD

**Issue by IanFLee** [tensorflow/community#338]
I need early tensorflow to train a gpt2 model, becase tf versions > 2 don't include .contrib. I need the graph_editor, which apparently didn't get a f unction in  versions 2+

I have also tried to just download the earlier tensorflow versions, however the only way I can do that is by downgrading Python versions from 3.8 to ~3.5.6 and that becomes its own mess because for some reason that isn't working either.

Is there nothing else I can assign? Am I missing something?

`import tensorflow.contrib.graph_editor as ge`
and change to
`import tensorflow.graph_editor as ge` ?

**Comment by bhack** [comment]
You can check https://github.com/CODAIT/graph_def_editor

**Comment by theadactyl** [comment]
We don't offer technical support on this repository. I recommend you create a topic in the TensorFlow Forum: https://discuss.tensorflow.org/
