### ISSUE TITLE
How to read Parquet gzip file in tensorflow dataset API

### ISSUE THREAD

**Issue by rshah1990** [tensorflow/community#345]
Hi Team,

I have multiple Parquet file in Gzip format which I have to read in using Tensor flow dataset API, I could not find any standard function in Dataset API does that, do we have any alternative for this.  I want to use Interleave to get better performance.

**Comment by theadactyl** [comment]
We don't offer technical support on this repository. I recommend you create a topic in the TensorFlow Forum: https://discuss.tensorflow.org/
