### ISSUE TITLE
Save a Tensor

### ISSUE THREAD

**Issue by somum** [tensorflow/community#347]
I have a tensor variable like

vb = tf.Variable(tf.zeros([visibleUnits]), tf.float32)

Data shape of vb looks like :
 
<tf.Tensor: shape=(,), dtype=float32, numpy=
array([,]], dtype=float32)>

I want to save this vb locally for further use any solution? Thank you

**Comment by kumaradityaka** [comment]
Create a Saver object : ` tf.train.Saver() `
In a session call `saver.save()` function to save the variable on the disk.

**Comment by theadactyl** [comment]
We don't offer technical support on this repository. I recommend you create a topic in the TensorFlow Forum: https://discuss.tensorflow.org/
