### ISSUE TITLE
tensorflow models/face landmarks detection

### ISSUE THREAD

**Issue by lghasemzadeh** [tensorflow/community#348]
Hello,

Do the tensorflow face landmarks detection and Iris landmarks models work on Infrared/grayscal image/video? I have a camera which captures Infrared streams, can I run this model over the infrared videos that I recorded with that camera? does the model work the same as when it works with RGB videos or real-time RGB streams.  @tensorflow @tensorflow-models/face-landmarks-detection @tensorflow-models/facemesh  
here is the link to the library:
https://blog.tensorflow.org/2020/11/iris-landmark-tracking-in-browser-with-MediaPipe-and-TensorFlowJS.html

**Comment by bhack** [comment]
I suggest to ask this in the Mediapipe repo https://github.com/google/mediapipe/ /cc @ematejska we can close this.
