### ISSUE TITLE
How to use distribution strategy at the time of production?

### ISSUE THREAD

**Issue by divyanshugit** [tensorflow/community#361]
I want to use distributed strategy at the time of production. Can you please help out with this? I am using **amazon sagemaker** `conda_amazonei_tensorflow2_p36` as a kernel.

**Comment by theadactyl** [comment]
We don't offer technical support on this repository. I recommend you create a topic in the TensorFlow Forum: https://discuss.tensorflow.org/

**Comment by theadactyl** [comment]
w
