### ISSUE TITLE
Unable to see the documentation!

### ISSUE THREAD

**Issue by divyanshugit** [tensorflow/community#362]
The link to the documentation is [here](https://www.tensorflow.org/versions/r0.11/how_tos/using_gpu/index.html#allowing-gpu-memory-growth)
![Screenshot (283)](https://user-images.githubusercontent.com/53843818/109631334-dd553c80-7b6b-11eb-9118-3b5d9f0d25d6.png)

**Comment by suryadesu** [comment]
> The link to the documentation is [here](https://www.tensorflow.org/versions/r0.11/how_tos/using_gpu/index.html#allowing-gpu-memory-growth)
> ![Screenshot (283)](https://user-images.githubusercontent.com/53843818/109631334-dd553c80-7b6b-11eb-9118-3b5d9f0d25d6.png)

Hi,
I think that the link points to tensorflow version of v0.11 which I don't think is part of tensorflow.org anymore. If you are looking out for reference about memory growth in the latest version, I would suggest you to take a look at [set_memory_growth](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth)
However, if your question is about tensorflow v0.11, then I hope this [link](https://tensorflow.github.io/rust/tensorflow/) can help.
