### ISSUE TITLE
How do I connect with GSoC 2021 Mentors?

### ISSUE THREAD

**Issue by Kareem-negm** [tensorflow/community#374]
Hi,
 I am Kareem Negm, a GSoC 2020 aspirant 
I've been preparing myself for over a year for this summer with TensorFlow. 

But now I have a lot of trouble communicating with the mentors. 
I've been trying for weeks to get more information about the project I've chosen from the projects list [here](https://docs.google.com/document/d/1TmiAqksKE9HqLll9y2j3vozToh7DnzlpP_EVJ2uGvVY/edit#), but to no avail.

I wish if someone was helping me with more information so That I could finish my proposal 

Thanks in advance

**Comment by Ashvith** [comment]
Hey, I am interested for the same as well. I want to port/improve TensorFlow in Ruby, if that's okay? But sadly, there aren't any proper resources, or even a Slack group to talk to mentors?

**Comment by ben-xD** [comment]
I don't even know how you got that link, its really hard for me to get involved.

**Comment by Ashvith** [comment]
> I don't even know how you got that link, its really hard for me to get involved.

Same mate. I am surprised as well.
