### ISSUE TITLE
sample_weight in model.fit() does not work on Tensorflow 2.1

### ISSUE THREAD

**Issue by jshu12** [tensorflow/community#378]
I'm trying to use sample_weight in the model.fit() function, and it doesn't work on Tensorflow 2.1. The bug is fixed on Tensorflow 2.2 and later. But for various reasons, my team prefers to keep using TF 2.1. Can you patch TF2.1 with the fix, or show me how to do it myself?

Here's my code:

```
import numpy as np
import tensorflow as tf

Model = tf.keras.models.Model
Input = tf.keras.layers.Input
Conv2D = tf.keras.layers.Conv2D
strategy = tf.distribute.MirroredStrategy()

input_size = 32

with strategy.scope():
  input_layer = Input(shape=(input_size,input_size,1))
  output_layer = Conv2D(1, (3,3), padding='same', activation='tanh')(input_layer)
  model = Model(inputs=input_layer, outputs=output_layer)
  optimizer = tf.keras.optimizers.Adam()
  loss= 'mean_absolute_error'
  model.compile(loss=loss,
                optimizer=optimizer,
                metrics=['mae','mse'])

x_train = np.random.rand(5,input_size,input_size,1)
y_train = np.random.rand(5,input_size,input_size,1)
sample_weight = np.array([1,2,3,4,5])

history = model.fit(x_train, y_train, sample_weight=sample_weight, batch_size=1, epochs=50, verbose=1)

```

Here's the error message from TF 2.1:

`ValueError: weights can not be broadcast to values. values.rank=3. weights.rank=1. values.shape=(1, 32, 32). weights.shape=(1,).`

**Comment by yarri-oss** [comment]
@jshu12 Can you please file this issue on the main TensorFlow repo https://github.com/tensorflow/tensorflow/issues Thanks!
