### ISSUE TITLE
Tensorflow 2.3 or 2.4 installation MacOs 10.11.16 

### ISSUE THREAD

**Issue by o0stsou0o** [tensorflow/community#383]
I have had trouble installing tensorflow 2.3 and on my Mac.  I've tried both in a virtual environment and a conda environment.  I've also taken into consideration python2 and python3.  If I pip install, I get a tensorflow 1.8 installation in python3 and when I conda install I get a tensorflow 2.0.  If I pip install an upgrade, I get a strange error in interactive python3 upon importing:

File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib

During handling of the above exception, another exception occurred:

"Traceback (most recent call last):
File "", line 1, in
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/init.py", line 41, in
from tensorflow.python.tools import module_util as _module_util
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/init.py", line 40, in
from tensorflow.python.eager import context
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/eager/context.py", line 35, in
from tensorflow.python import pywrap_tfe
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in
from tensorflow.python import pywrap_tensorflow
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 83, in
raise ImportError(msg)
ImportError: Traceback (most recent call last):
File "/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in
from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: dlopen(/Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 6): Symbol not found: _SecKeyCopyExternalRepresentation
Referenced from: /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib
Expected in: /System/Library/Frameworks/Security.framework/Versions/A/Security
in /Users/blah/anaconda3/envs/test2/lib/python3.7/site-packages/tensorflow/python/../libtensorflow_framework.2.dylib"

Would anybody know what the problem may be?  Thanks.

**Comment by yarri-oss** [comment]
@o0stsou0o can you please file TensorFlow related issues at https://github.com/tensorflow/tensorflow/issues ? Thanks!

**Comment by callmekofi** [comment]
Could you set up an Anaconda environment and try installing tensorflow from there. check [here](https://github.com/apple/tensorflow_macos)
