### ISSUE TITLE
SIG Add-ons: Finalize documentation and examples, and publish first package.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/community#60]
TF 2.0 might have deprecated `tf.contrib`, but much of its functionality is widely-used and important to the TensorFlow community. **Addons** is a repository of those bleeding edge contributions that conform to well-established API patterns, but implement new functionality not available in core TensorFlow. 

For more information on Addons, check out their [GitHub repo](https://github.com/tensorflow/addons), their [community charter](https://github.com/tensorflow/community/blob/master/sigs/addons/CHARTER.md), and their [mailing group](https://groups.google.com/a/tensorflow.org/forum/#!forum/addons).

**Comment by seanpmorgan** [comment]
First package is [released](https://github.com/tensorflow/addons/releases). Documentation and examples will continue to be updated as the project matures.

**Comment by dynamicwebpaige** [comment]
Thanks for the update, @seanpmorgan! Am closing out this issue. 😄 

Please try out [TensorFlow Addons](https://www.github.com/tensorflow/addons) and let us know what you think.
