### ISSUE TITLE
Tracking Issue for PPC64LE builds

### ISSUE THREAD

**Issue by wdirons** [tensorflow/community#7]
Tracking Issue for PPC64LE builds

Following the new process in https://github.com/tensorflow/community/blob/master/sigs/build/community-builds.md
creating this issue to track the existing CPU and GPU community supported builds for PPC64LE.

Test Plan:
CPU and GPU Builds for each commit triggered by GITscm polling.
Nightly build and unit test runs for CPU and GPU Builds.
Issues opened for failing test.

Documentation and examples:
Artifacts published as a results of these builds can be downloaded from the Jenkins server jobs for nightly artifacts and stable release artifacts.

We are working on uploading docker images to the ibmcom/tensorflow namespace. 

Support plan:
@wdirons - Primary contact for GPU build/test failures
@sandipmgiri - Primary contact for CPU build/test failures
@tedhtchang - Primary contact for build failures that are environment related.
@jayfurmanek
@JonTriebenbach

Current builds:
https://powerci.osuosl.org/user/wdirons/my-views/view/TensorFlow%20Jobs/

**Comment by sub-mod** [comment]
Under which project name will the wheel files be published in pypi ?

**Comment by wdirons** [comment]
@sub-mod, I don't know yet which project name we will use for pypi. Ideally it would be tensorflow (for release builds) but for that to happen we would need to work out a process with the Tensorflow team.

**Comment by gunan** [comment]
@ewilderj @martinwicke and @gunan 
Thanks for creating the bug, and including all the contacts!

**Comment by bhack** [comment]
Can we close this?

**Comment by bhack** [comment]
Can we close this?

**Comment by jayfurmanek** [comment]
Thanks yea, I think we can close this tracking issue.

**Comment by bhack** [comment]
@ematejska can you close this?
