### ISSUE TITLE
Import Error: cannot import name 'model_utils'

### ISSUE THREAD

**Issue by wendongqu** [tensorflow/community#92]
import tensorflow as tf
tf.__version__( got  1.13.1)
import tensorflow_probability as tfp

got error:

File "c:\program files\python36\lib\site-packages\tensorflow_estimator\python\estimator\model_fn.py", line 33, in <module>
    from tensorflow.python.saved_model import model_utils as export_utils

ImportError: cannot import name 'model_utils'

basically, there is no model_utils subfolder or file under tensorflow/python/saved_model

thanks.

**Comment by jackd** [comment]
Workaround: I had a similar issue, resolved it by reinstalling tensorflow-estimator

```python
pip install -I tensorflow-estimator
```

**Comment by xiaoshuaigeasdf** [comment]
same problem.
Comes from the tensorflowjs import. It does have a relationship with ‘estimator’, but reinstallation does not solve the problem.

**Comment by PriyanshChaudhary** [comment]
yes. It shows me a similar error when  I use this:
`tf.keras.estimator`

**Comment by ewilderj** [comment]
Apologies, but this issue tracker is for TF Community governance. I encourage you to address questions to the tensorflow/tensorflow issue tracker, discuss@tensorflow.org or StackOverflow.

**Comment by Adblu** [comment]
I had to reinstall tensorflow from 1.13 to 1.14 and that worked for me.
