### ISSUE TITLE
WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0. For more information, please see:   * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md   * https://github.com/tensorflow/addons If you depend on functionality not listed there, please file an issue.

### ISSUE THREAD

**Issue by shangyueweiliang** [tensorflow/community#93]

**Comment by jackwish** [comment]
I guess the *community* repo is not for *supporting like* things. Maybe try stackoverflow?

**Comment by ewilderj** [comment]
Apologies, but this issue tracker is for TF Community governance. I encourage you to address questions to the tensorflow/tensorflow issue tracker, discuss@tensorflow.org or StackOverflow.
